name: Docker Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t asawarinavle/student-management:${{ github.ref_name }} .
          docker tag asawarinavle/student-management:${{ github.ref_name }} asawarinavle/student-management:${{ steps.vars.outputs.sha_short }}

      - name: Push Docker Images
        run: |
          docker push AsawariNavle/student-management:${{ github.ref_name }}
          docker push asawariNavle/student-management:${{ steps.vars.outputs.sha_short }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true